### ISSUE TITLE
提高打印预览速度

### ISSUE THREAD

**Issue by FreeVB** [Fei-Sheng-Wu/PrintDialogX#1]
很好的打印预览功能，界面也不错，
大神能在提高打印预览速度方面优化一下不？

**Comment by Fei-Sheng-Wu** [comment]
这个项目不再维护，但是我将抽空看看是否可以提高速度。

**Comment by Fei-Sheng-Wu** [comment]
我提交了新版本，应该有所改进，但可能不是非常有效。大多数时间实际上不是耗费在预览生成上，而是在文档生成上。我将会继续研究下这个问题，希望能找到更好的解决方案。

**Comment by FreeVB** [comment]
谢谢你的更新，可能我的描述不是太清楚，应该就是你说的预览生成。

**Comment by Fei-Sheng-Wu** [comment]
抱歉，速度问题无法在短期内解决。

Sorry, the problem of speed won't be able to be solved in a short term.

**Comment by Fei-Sheng-Wu** [comment]
在Github上提交的最新版本（v1.5.2.0）继续提高了速度，希望它能解决您的问题！

**Comment by Fei-Sheng-Wu** [comment]
@FreeVB

这是我在计算机上拍摄的屏幕记录，您可以看到它的效率有多高。

This is a screen record I took on my computer, you can see how efficient it is.

https://user-images.githubusercontent.com/36951947/108442713-2082e780-721d-11eb-8c51-0e96d1915b9c.mp4
