### ISSUE TITLE
Cannot recognize custom page size

### ISSUE THREAD

**Issue by csm12s** [Fei-Sheng-Wu/PrintDialogX#2]
Can handle page size like psk:ISOA4, cannot recognize custom page size like  ns0000:User0000000340, it is now commonly used in new printers

**Comment by Fei-Sheng-Wu** [comment]
> fixed, modified System.Printing.PrintQueue to support label priter, added some new options
> 
> https://github.com/csm12s/WPF-Label-Print

Support for custom paper sizes has now been added, referencing the above code. Thank you!
