### ISSUE TITLE
it can not support BitmapImage.StreamSource

### ISSUE THREAD

**Issue by Charltsing** [Fei-Sheng-Wu/PrintDialogX#3]
PrintPage.xaml.cs---PrintPage---string xaml = XamlWriter.Save(page);

it can not support BitmapImage.StreamSource

**Comment by flydream3618** [comment]
我修复了这个问题，原因：XamlWriter无法对StreamSource进行序列化，因此调用XamlWriter会导致StreamSource属性被忽略。

我的临时方案：增加XamlWriter解析前后回调，即新增回调函数：PageCloneBefore、PageCloneAfter放在所有需要XamlWriter的地方，当触发PageCloneBefore时，传入默认图片资源，当调用PageCloneAfter传入有效的StreamSource。

示例：

**插入回调：**
![image](https://github.com/Fei-Sheng-Wu/PrintDialogX/assets/22423509/8ea4328f-e5f0-4b2b-866c-39955ccd43a2)





**回调实现：**

![image](https://github.com/Fei-Sheng-Wu/PrintDialogX/assets/22423509/2d2d8bf4-6e54-4b65-9a63-177b298b23fc)

![image](https://github.com/Fei-Sheng-Wu/PrintDialogX/assets/22423509/02d67b08-e2c9-40f9-a68f-70afe26c0756)



这样，仅需处理有异常的地方就可以了

因为整个的界面被我改成全中文版了，因此如果需要代码请给我留言

**Comment by Charltsing** [comment]
这个项目的错误太多，我几乎重写了全部的核心代码。包括打印机读取，打印文档创建，顺便修复了微软更新wpf安全性导致预览无法显示的问题。

这个序列化也不需要了

**Comment by Fei-Sheng-Wu** [comment]
This problem should be fixed now with the new update (https://github.com/Fei-Sheng-Wu/PrintDialogX/tree/2.0.1), all "Image" elements should be working as intended.
