### ISSUE TITLE
請問如何render PDF?

### ISSUE THREAD

**Issue by yuessir** [Fei-Sheng-Wu/PrintDialogX#4]
請問如何render PDF?
要先轉XPS?
我轉成XPS後仍然無法render 
請問可以給一個範例嗎?

**Comment by Fei-Sheng-Wu** [comment]
这个项目没有对 PDF 渲染的直接支持。如果是用户使用的话，可以使用 “Microsoft Print to PDF” 虚拟打印机选项以打印成 PDF 文件。
