### ISSUE TITLE
Project can not launch 

### ISSUE THREAD

**Issue by nyendwa** [Fei-Sheng-Wu/PrintDialogX#5]
Your project look amazing and I want to learn from it because I am working on something similar. Kindly let me know how to launch it because I am getting an impression it is a class library and cannot be launched. I am using VS 2022

**Comment by Fei-Sheng-Wu** [comment]
Hi, you can set PrintDialogX.Test as the startup project in Visual Studio to run it. Since PrintDialogX is indeed a class library, it needs to be referenced and called from another project.
